### ISSUE TITLE
Compile issue [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [emurray2/EVMusic-Rack#1]
``
g++ -o plugin.dll build/src/ModularForecast.cpp.o build/src/plugin.cpp.o -shared -L../../.. -lRack
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/src/ModularForecast.cpp.o: in function `ModularForecastDisplay::drawFramebuffer()':
C:\_Projects\VCVRack\V1\Rack\plugins\EVMusic-Rack\EVMusic/src/ModularForecast.cpp:40: undefined reference to `glViewport'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\_Projects\VCVRack\V1\Rack\plugins\EVMusic-Rack\EVMusic/src/ModularForecast.cpp:41: undefined reference to `glClearColor'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\_Projects\VCVRack\V1\Rack\plugins\EVMusic-Rack\EVMusic/src/ModularForecast.cpp:42: undefined reference to `glClear'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\_Projects\VCVRack\V1\Rack\plugins\EVMusic-Rack\EVMusic/src/ModularForecast.cpp:43: undefined reference to `glColor3f'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\_Projects\VCVRack\V1\Rack\plugins\EVMusic-Rack\EVMusic/src/ModularForecast.cpp:44: undefined reference to `glRectf'
collect2.exe: error: ld returned 1 exit status
make: *** [../../../compile.mk:59: plugin.dll] Error 1
``

**Comment by emurray2** [comment]
Interesting... I do not have a windows machine, so I will have to get a VM sometime and experiment with building for the Windows architecture. It looks like it is missing a library or something.

Edit: I realized I never set up the build environment for Windows, as I intended to create this on my Mac as a personal project.

**Comment by emurray2** [comment]
@SteveRussell33 I figured it out! Long story short, when compiling on Windows, I think you need to link the OpenGL libraries inside Makefile. You can do this by adding the necessary flags to `LDFLAGS`. See this for more details: [https://discourse.glfw.org/t/cannot-run-glfw-example-on-windows-10/1090/3](https://discourse.glfw.org/t/cannot-run-glfw-example-on-windows-10/1090/3). I tried linking those, and I was able to compile the dll file in MSYS2 with the MinGW 64-bit shell on Windows 10. Although, some of the flags in the post I linked above were not recognized by the compiler, so I just removed them. I will update the Makefile and code on this repo shortly with these fixes. Let me know if this solves the issue for you. I am a novice developer, so any feedback from other people helps me! 

Best, 
Evan Murray

**Comment by emurray2** [comment]
I'm going to close this issue for now since it's been lingering for a while now. If anyone else still has trouble compiling the latest commit on Windows 10, please reopen this.

**Comment by SteveRussell33** [comment]
I can confirm that it now builds following your LDFLAGS fix.

Good job! Look forward to testing.
