### ISSUE TITLE
Plugin Manager integration issues

### ISSUE THREAD

**Issue by cschol** [emurray2/EVMusic-Rack#2]
Here are a few issues that need to be resolved before the plugin can be integrated in the Plugin Manager:

1. The files (specifically `Makefile`, `plugin.json`) must be available in the **root directory** of the repository, not in a sub-directory (in your case "AuraAudio").

2. You committed and pushed binary files (i.e. the .zip files) to the repository on Github. Just deleting them with a commit is **not enough** as the files are still in the repository history and enlarge the repo size unnecessarily. 

This needs to be fixed first before integration can proceed.

For both issues, I recommend you start with a **fresh** repo and fix the sub-directory issue and only commit to that repository what you really want. I also recommend using a `.gitignore` file to prevent committing binary files in the future.

**Comment by emurray2** [comment]
Sounds good! I just created a new repository with a `.gitignore` file and no binaries. Thank you for the helpful advice!
